export const CATEGORIES = [
  {
    name: "Tâm trạng",
    slug: "tam-trang",
    link: "/categories/tam-trang",
    count: 10,
    description: "Những suy nghĩ và cảm xúc đời thường",
    image: "/images/categories/tam-trang.jpg",
    alt: "Sóng biển nhẹ nhàng vỗ vào bờ",
  },
  {
    name: "Vi vu",
    slug: "vi-vu",
    link: "/categories/vi-vu",
    count: 10,
    description: "Những chuyến đi và nơi chốn đã ghé qua",
    image: "/images/categories/vi-vu.jpg",
    alt: "Phong cảnh núi non",
  },
  {
    name: "Suy nghĩ",
    slug: "suy-nghi",
    link: "/categories/suy-nghi",
    count: 10,
    description: "Những góc nhìn và chiêm nghiệm về cuộc sống",
    image: "/images/categories/suy-nghi.jpg",
    alt: "Trang sách và góc viết yên tĩnh",
  },
  {
    name: "Kỷ niệm",
    slug: "ky-niem",
    link: "/categories/ky-niem",
    count: 10,
    description: "Những khoảnh khắc và câu chuyện đáng nhớ",
    image: "/images/categories/ky-niem.jpg",
    alt: "Chiếc máy ảnh lưu giữ những khoảnh khắc",
  },
];

export const BLOG_POSTS = [
  {
    slug: "mot-ngay-cham-lai",
    categorySlug: "tam-trang",
    title: "Một ngày chậm lại",
    description: "Dành một chút thời gian để lắng nghe mình giữa những ngày bận rộn.",
    content: [
      "Sáng nay, mình không mở điện thoại ngay khi thức dậy. Mình kéo rèm, đun nước và nhìn ánh nắng chậm rãi đi qua bậu cửa. Những việc nhỏ ấy khiến buổi sáng bớt giống một cuộc chạy đua.",
      "Mình vẫn có công việc cần hoàn thành, nhưng thử làm từng việc một và nghỉ giữa những khoảng tập trung. Chậm lại không phải là bỏ cuộc; đó là cách mình nhận ra hôm nay mình cần gì để tiếp tục.",
    ],
    postedDate: "2026-09-20",
    readingTime: "4 phút đọc",
    tags: ["Đời thường", "Bình yên"],
  },
  {
    slug: "nhung-ngay-long-nhe-tenh",
    categorySlug: "tam-trang",
    title: "Những ngày lòng nhẹ tênh",
    description: "Niềm vui đôi khi đến từ những điều nhỏ bé mà ta thường bỏ qua.",
    content: [
      "Có những ngày chẳng có tin vui đặc biệt, vậy mà mình vẫn thấy dễ chịu. Người bán hàng nhớ món mình thường gọi, một người bạn gửi tấm ảnh buồn cười, trời vừa đủ mát để đi bộ về nhà.",
      "Tối đến, mình ghi những điều ấy vào một trang sổ. Khi để ý hơn, mình nhận ra niềm vui không hẳn ít đi; đôi khi mình chỉ quá bận để nhìn thấy nó đang ở ngay bên cạnh.",
    ],
    postedDate: "2026-10-01",
    readingTime: "3 phút đọc",
    tags: ["Cảm xúc"],
  },
  {
    slug: "hen-voi-nui-non",
    categorySlug: "vi-vu",
    title: "Hẹn với núi non",
    description: "Một chuyến đi giữa những con đường quanh co và khoảng trời rộng mở.",
    content: [
      "Chúng mình khởi hành khi thành phố còn ngái ngủ. Càng lên cao, những mái nhà càng thưa, thay vào đó là sườn núi và những vạt cây nối nhau đến tận chân trời. Mỗi khúc cua lại mở ra một cảnh khác.",
      "Ở điểm dừng cuối, cả nhóm ngồi xuống uống nước và ngắm mây trôi qua đỉnh núi. Không ai vội chụp thêm ảnh. Mình thích khoảnh khắc được nhìn thật lâu, để chuyến đi ở lại trong trí nhớ trước khi nằm trong điện thoại.",
    ],
    postedDate: "2026-09-25",
    readingTime: "6 phút đọc",
    tags: ["Du lịch", "Thiên nhiên"],
  },
  {
    slug: "di-de-tim-mot-khoang-lang",
    categorySlug: "vi-vu",
    title: "Đi để tìm một khoảng lặng",
    description: "Rời nhịp sống quen thuộc để khám phá một nơi chốn mới.",
    content: [
      "Mình chọn một nơi không quá xa và để lịch trình gần như trống. Buổi sáng đi dọc con đường nhỏ, buổi trưa nghỉ dưới hiên, buổi chiều tìm một quán có cửa sổ nhìn ra hàng cây.",
      "Chuyến đi không giải quyết hết những điều khiến mình lo. Nhưng khoảng cách với nhịp sống thường ngày giúp mình nghe rõ suy nghĩ hơn. Khi trở về, mình mang theo một thói quen mới: dành một khoảng yên tĩnh cho mỗi ngày.",
    ],
    postedDate: "2026-09-10",
    readingTime: "5 phút đọc",
    tags: ["Hành trình"],
  },
  {
    slug: "hoc-cach-lang-nghe",
    categorySlug: "suy-nghi",
    title: "Học cách lắng nghe",
    description: "Những điều ta nhận ra khi dành nhiều thời gian hơn để lắng nghe.",
    content: [
      "Trong một cuộc trò chuyện gần đây, mình nhận ra mình đang nghĩ đến câu trả lời khi bạn còn chưa nói hết. Mình đặt điện thoại xuống và thử chỉ nghe, không chen vào bằng một câu chuyện tương tự của bản thân.",
      "Những khoảng ngừng hóa ra cũng có ý nghĩa. Khi được dành thời gian, bạn kể thêm những điều trước đó chưa biết diễn đạt thế nào. Mình học được rằng có mặt trọn vẹn đôi khi hữu ích hơn một lời khuyên vội vàng.",
    ],
    postedDate: "2026-09-28",
    readingTime: "5 phút đọc",
    tags: ["Chiêm nghiệm"],
  },
  {
    slug: "khong-can-voi-vang",
    categorySlug: "suy-nghi",
    title: "Không cần vội vàng",
    description: "Mỗi người có một nhịp đi riêng, và ta có thể bước theo nhịp của mình.",
    content: [
      "Có lúc nhìn những cột mốc của người khác, mình thấy bản thân đang đứng yên. Nhưng nếu nhìn lại một năm trước, mình đã học được nhiều điều và cũng hiểu rõ hơn những việc mình không muốn theo đuổi.",
      "Mình thử đặt mục tiêu dựa trên cuộc sống của mình, thay vì một lịch trình tưởng tượng dành cho tất cả mọi người. Một bước nhỏ nhưng phù hợp vẫn là một bước đi. Hôm nay, mình cho phép bản thân tiến về phía trước mà không phải chạy.",
    ],
    postedDate: "2026-09-12",
    readingTime: "4 phút đọc",
    tags: ["Cuộc sống"],
  },
  {
    slug: "nhung-tam-anh-cu",
    categorySlug: "ky-niem",
    title: "Những tấm ảnh cũ",
    description: "Lật lại một album ảnh và nhớ về những ngày đã qua.",
    content: [
      "Trong lúc dọn tủ, mình tìm thấy một album đã lâu không mở. Có tấm ảnh hơi nhòe, có tấm chỉ chụp một góc bàn ăn, nhưng nhìn vào là nhớ ngay tiếng nói và ánh sáng của ngày hôm ấy.",
      "Mình ghi thêm ngày tháng và tên những người trong ảnh lên một mảnh giấy nhỏ. Ký ức không cần tấm hình hoàn hảo để trở lại; đôi khi chính những chi tiết vụng về mới giữ được cảm giác chân thật nhất.",
    ],
    postedDate: "2026-09-22",
    readingTime: "3 phút đọc",
    tags: ["Ảnh", "Ký ức"],
  },
  {
    slug: "mua-he-nam-ay",
    categorySlug: "ky-niem",
    title: "Mùa hè năm ấy",
    description: "Một câu chuyện nhỏ về mùa hè, bạn bè và những khoảnh khắc còn ở lại.",
    content: [
      "Mùa hè ấy, chúng mình có nhiều thời gian và rất ít kế hoạch. Buổi chiều thường gặp nhau ở đầu ngõ, đạp xe qua những con đường quen rồi ghé mua một món lạnh để chia nhau.",
      "Bây giờ mỗi người ở một nơi, cuộc hẹn phải sắp xếp trước nhiều tuần. Thỉnh thoảng nhắc lại một chuyện cũ, cả nhóm vẫn cười như ngày đó. Có lẽ điều còn lại không chỉ là mùa hè, mà là cảm giác từng có nhau trong những ngày rất đỗi bình thường.",
    ],
    postedDate: "2026-09-05",
    readingTime: "4 phút đọc",
    tags: ["Ký ức"],
  },
  {
    slug: "buoi-sang-ben-cua-so",
    categorySlug: "tam-trang",
    title: "Buổi sáng bên cửa sổ",
    description: "Một tách trà ấm và ánh nắng đầu ngày đủ để lòng dịu lại.",
    content: [
      "Mình kê chiếc ghế sát cửa sổ và pha một tách trà. Bên ngoài, hàng xóm đang tưới cây, tiếng xe còn thưa và nắng mới chạm vào những chiếc lá. Một buổi sáng quen thuộc bỗng trở nên đáng nhớ.",
      "Trước khi bắt đầu công việc, mình ngồi thêm vài phút mà không làm gì khác. Khoảng nghỉ ngắn ấy giúp mình bước vào ngày mới nhẹ nhàng hơn, như thể đã kịp chào chính mình trước khi trả lời mọi người.",
    ],
    postedDate: "2026-09-02",
    readingTime: "3 phút đọc",
    tags: ["Bình yên"],
  },
  {
    slug: "khi-con-mua-ghe-qua",
    categorySlug: "tam-trang",
    title: "Khi cơn mưa ghé qua",
    description: "Nghe tiếng mưa và để những lo âu trôi đi một chút.",
    content: [
      "Cơn mưa đến đúng lúc mình định ra ngoài. Mình cất lại chiếc túi, mở hé cửa và nghe tiếng nước rơi trên mái hiên. Kế hoạch đổi khác, nhưng lần này mình không thấy cần phải khó chịu vì điều đó.",
      "Trong lúc chờ mưa ngớt, mình pha nước ấm và viết ra những việc còn dang dở. Từng việc trên giấy rõ ràng hơn những lo lắng trong đầu. Khi trời sáng lại, mình biết điều gì cần làm trước và điều gì có thể để ngày mai.",
    ],
    postedDate: "2026-09-04",
    readingTime: "4 phút đọc",
    tags: ["Cảm xúc", "Mưa"],
  },
  {
    slug: "cho-minh-mot-ngay-nghi",
    categorySlug: "tam-trang",
    title: "Cho mình một ngày nghỉ",
    description: "Không cần làm điều gì lớn lao trong một ngày dành riêng cho mình.",
    content: [
      "Mình từng biến ngày nghỉ thành một danh sách công việc khác: dọn dẹp, mua sắm, học thêm, trả lời những tin nhắn còn thiếu. Đến tối, mình lại mệt và tự hỏi thời gian nghỉ đã đi đâu.",
      "Hôm nay mình chỉ chọn một việc cần thiết, còn lại để trống. Mình ngủ đủ, ăn chậm và đọc vài trang sách. Không phải ngày nào cũng cần có thành quả để xứng đáng được ghi nhớ.",
    ],
    postedDate: "2026-09-06",
    readingTime: "3 phút đọc",
    tags: ["Đời thường"],
  },
  {
    slug: "niem-vui-tu-can-bep-nho",
    categorySlug: "tam-trang",
    title: "Niềm vui từ căn bếp nhỏ",
    description: "Nấu một món quen và tìm lại cảm giác ấm áp giữa ngày dài.",
    content: [
      "Sau một ngày dài, mình vào bếp nấu món canh quen. Rửa rau, thái từng miếng nhỏ và chờ nồi nước sôi là những việc đơn giản, nhưng khiến tâm trí bớt chạy theo công việc chưa xong.",
      "Bữa ăn không cầu kỳ, chỉ có canh nóng và cơm vừa chín. Mình ngồi xuống ăn khi món ăn còn ấm và thấy việc chăm sóc bản thân đôi khi bắt đầu từ một căn bếp nhỏ như thế.",
    ],
    postedDate: "2026-09-08",
    readingTime: "4 phút đọc",
    tags: ["Đời thường", "Niềm vui"],
  },
  {
    slug: "nhung-luc-thay-minh-met",
    categorySlug: "tam-trang",
    title: "Những lúc thấy mình mệt",
    description: "Học cách nhận ra giới hạn và đối xử nhẹ nhàng hơn với bản thân.",
    content: [
      "Có những hôm việc nhỏ cũng khiến mình mất nhiều sức hơn thường lệ. Trước đây, mình thường cố làm tiếp và trách bản thân thiếu cố gắng. Giờ mình thử dừng lại để xem mình đã ăn, ngủ và nghỉ đủ chưa.",
      "Mình giảm bớt những việc chưa gấp và nói rõ khi cần thêm thời gian. Nhận ra giới hạn không làm mình kém đi; nó giúp mình giữ sức cho những điều quan trọng và đối xử tử tế hơn với cả bản thân lẫn người khác.",
    ],
    postedDate: "2026-09-14",
    readingTime: "5 phút đọc",
    tags: ["Cảm xúc"],
  },
  {
    slug: "mot-loi-hoi-tham",
    categorySlug: "tam-trang",
    title: "Một lời hỏi thăm",
    description: "Đôi khi một câu hỏi giản dị cũng có thể làm sáng cả ngày.",
    content: [
      "Giữa một buổi chiều bận rộn, mình nhận được tin nhắn hỏi hôm nay có ổn không. Người gửi chẳng biết mình đang có một ngày khó khăn, nhưng câu hỏi ấy khiến mình thấy có thể nói thật rằng mình đang hơi mệt.",
      "Cuộc trò chuyện chỉ kéo dài vài phút. Sau đó, mình nhắn cho một người bạn đã lâu chưa gặp. Không cần đợi một dịp đặc biệt để hỏi thăm nhau; những kết nối nhỏ vẫn có thể giữ cho ngày thường bớt lạnh.",
    ],
    postedDate: "2026-09-16",
    readingTime: "3 phút đọc",
    tags: ["Kết nối"],
  },
  {
    slug: "buoc-chan-cuoi-chieu",
    categorySlug: "tam-trang",
    title: "Bước chân cuối chiều",
    description: "Một vòng đi bộ qua phố quen để sắp xếp lại những cảm xúc trong lòng.",
    content: [
      "Mình ra ngoài lúc nắng đã dịu, không mang tai nghe và cũng không chọn đích đến. Con phố vẫn như mọi hôm, nhưng đi chậm giúp mình thấy một giàn cây mới và nghe tiếng trò chuyện từ quán nước đầu ngõ.",
      "Sau một vòng đi bộ, những suy nghĩ rối rắm không biến mất hoàn toàn, nhưng chúng không còn chen nhau nữa. Mình trở về, uống một cốc nước và chọn làm từng việc. Đôi khi một bước chân là đủ để bắt đầu thay đổi nhịp ngày.",
    ],
    postedDate: "2026-09-18",
    readingTime: "4 phút đọc",
    tags: ["Bình yên", "Đời thường"],
  },
  {
    slug: "giu-lai-mot-chut-am-ap",
    categorySlug: "tam-trang",
    title: "Giữ lại một chút ấm áp",
    description: "Ghi lại những điều tử tế nhỏ bé đã gặp trong tuần.",
    content: [
      "Tuần này, một người giữ cửa khi tay mình đang đầy đồ, một đồng nghiệp nhắc mình nghỉ trưa, một người bạn nhớ điều mình từng kể. Những việc ấy rất nhỏ, dễ trôi qua nếu mình không ghi lại.",
      "Mình dành một trang sổ cho những điều tử tế đã nhận. Đọc lại, mình thấy cuộc sống không chỉ có những việc cần giải quyết. Mình cũng muốn tiếp nối sự ấm áp ấy bằng những hành động vừa sức mỗi ngày.",
    ],
    postedDate: "2026-09-24",
    readingTime: "3 phút đọc",
    tags: ["Niềm vui"],
  },
  {
    slug: "buoi-sang-o-thanh-pho-la",
    categorySlug: "vi-vu",
    title: "Buổi sáng ở thành phố lạ",
    description: "Khám phá những con phố mới khi hàng quán vừa mở cửa.",
    content: [
      "Mình thức dậy sớm hơn thường lệ và đi bộ ra khỏi nơi nghỉ. Thành phố lạ hiện ra qua tiếng cửa cuốn, mùi bánh nóng và những người đang bắt đầu ngày làm việc. Không có điểm tham quan nào trong lịch trình buổi sáng ấy.",
      "Mình ngồi ăn ở một quán nhỏ và hỏi đường đến khu chợ gần đó. Những lời chỉ dẫn thân thiện khiến nơi xa lạ bớt xa. Khi trở về, điều mình nhớ nhất lại là buổi sáng giản dị được sống cùng nhịp của thành phố.",
    ],
    postedDate: "2026-09-02",
    readingTime: "5 phút đọc",
    tags: ["Du lịch", "Thành phố"],
  },
  {
    slug: "con-duong-ven-bien",
    categorySlug: "vi-vu",
    title: "Con đường ven biển",
    description: "Theo một cung đường đầy gió và dừng lại trước màu xanh của biển.",
    content: [
      "Con đường ôm theo bờ biển, lúc gần những ngôi nhà nhỏ, lúc mở ra khoảng nước xanh rộng. Chúng mình dừng ở một chỗ đỗ an toàn, đi bộ xuống bãi cát và đứng nghe gió trước khi tiếp tục hành trình.",
      "Bữa trưa là một món đơn giản ở quán ven đường. Mình không cố ghé hết các điểm đã lưu mà dành thêm thời gian cho nơi mình thích. Chuyến đi dễ chịu hơn khi lịch trình có chỗ cho những lần dừng bất chợt.",
    ],
    postedDate: "2026-09-04",
    readingTime: "6 phút đọc",
    tags: ["Biển", "Hành trình"],
  },
  {
    slug: "mot-dem-cam-trai",
    categorySlug: "vi-vu",
    title: "Một đêm cắm trại",
    description: "Dựng lều, nấu bữa tối và ngắm bầu trời xa ánh đèn thành phố.",
    content: [
      "Chúng mình đến khu cắm trại khi trời còn sáng để có thời gian dựng lều và chuẩn bị bữa tối. Mỗi người làm một việc, từ sắp đồ đến rửa rau. Bữa ăn ngoài trời vì thế có thêm niềm vui cùng nhau làm ra nó.",
      "Đêm xuống, cả nhóm ngồi nhìn những khoảng sao giữa mây và nói chuyện thật chậm. Sáng hôm sau, chúng mình thu dọn rác và kiểm tra lại chỗ nghỉ trước khi rời đi. Mình muốn lần sau trở lại, nơi này vẫn yên lành như lúc mới đến.",
    ],
    postedDate: "2026-09-06",
    readingTime: "5 phút đọc",
    tags: ["Cắm trại", "Thiên nhiên"],
  },
  {
    slug: "ghe-tham-ngoi-lang-nho",
    categorySlug: "vi-vu",
    title: "Ghé thăm ngôi làng nhỏ",
    description: "Những mái nhà yên tĩnh và câu chuyện gặp dọc đường.",
    content: [
      "Ngôi làng có con đường hẹp, những mái hiên thấp và vài quán nhỏ mở cửa từ sớm. Mình đi bộ, chào những người gặp trên đường và hỏi trước khi chụp ảnh một góc sân có nhiều hoa.",
      "Một người chủ quán kể về phiên chợ cuối tuần và mùa cây đang ra quả. Câu chuyện khiến cảnh vật có thêm chiều sâu. Mình rời đi với ít ảnh hơn dự định nhưng nhớ rõ hơn những người đã làm nên nhịp sống của nơi ấy.",
    ],
    postedDate: "2026-09-08",
    readingTime: "4 phút đọc",
    tags: ["Du lịch"],
  },
  {
    slug: "chuyen-tau-cuoi-tuan",
    categorySlug: "vi-vu",
    title: "Chuyến tàu cuối tuần",
    description: "Nhìn phong cảnh qua ô cửa và tận hưởng một hành trình chậm rãi.",
    content: [
      "Mình đặt một chuyến tàu buổi sáng và mang theo cuốn sách chưa đọc xong. Khi tàu ra khỏi thành phố, ngoài cửa sổ lần lượt là những mái nhà, ruộng xanh và các ga nhỏ. Cuốn sách nằm yên trên đùi khá lâu.",
      "Không phải tự lái xe, mình có thời gian quan sát những đoạn đường thường chỉ lướt qua. Đến nơi, mình thấy hành trình đã là một phần của kỳ nghỉ, chứ không chỉ là khoảng chờ trước khi chuyến đi bắt đầu.",
    ],
    postedDate: "2026-09-14",
    readingTime: "5 phút đọc",
    tags: ["Tàu hỏa", "Hành trình"],
  },
  {
    slug: "di-bo-giua-rung-xanh",
    categorySlug: "vi-vu",
    title: "Đi bộ giữa rừng xanh",
    description: "Một lối mòn dưới tán cây và những âm thanh dễ bỏ quên.",
    content: [
      "Chúng mình chọn một lối đi được đánh dấu và kiểm tra thời tiết trước khi xuất phát. Dưới tán cây, không khí mát hơn và mỗi bước chân chạm vào lớp lá khô nghe rất rõ. Cả nhóm giảm tốc để đi cùng nhau.",
      "Ở một khoảng nghỉ, mình cất điện thoại và nghe tiếng chim, tiếng gió, tiếng nước ở xa. Khu rừng có nhiều chuyển động hơn mình tưởng. Trở về theo lối cũ, mình vẫn thấy những điều mới vì đã bắt đầu chú ý hơn.",
    ],
    postedDate: "2026-09-16",
    readingTime: "6 phút đọc",
    tags: ["Thiên nhiên"],
  },
  {
    slug: "quan-ca-phe-tren-doi",
    categorySlug: "vi-vu",
    title: "Quán cà phê trên đồi",
    description: "Một điểm dừng nhỏ để ngắm mây và trò chuyện cùng bạn đồng hành.",
    content: [
      "Quán nằm ở cuối một đoạn đường lên dốc, có vài chiếc bàn hướng ra thung lũng. Chúng mình gọi đồ uống và chọn chỗ ngồi ngoài hiên. Mây đi qua chậm đến mức có thể nhìn thấy bóng chúng đổi trên sườn đồi.",
      "Cuộc trò chuyện không có chủ đề cố định, chỉ là những chuyện gần đây chưa kịp kể. Mình thích những điểm dừng không đòi hỏi phải làm gì thêm. Một tách cà phê và thời gian dành cho nhau đã đủ thành một phần đáng nhớ của chuyến đi.",
    ],
    postedDate: "2026-09-18",
    readingTime: "4 phút đọc",
    tags: ["Cà phê", "Du lịch"],
  },
  {
    slug: "hanh-ly-cho-chuyen-di-ngan",
    categorySlug: "vi-vu",
    title: "Hành lý cho chuyến đi ngắn",
    description: "Mang theo vừa đủ để dành chỗ cho những trải nghiệm mới.",
    content: [
      "Trước chuyến đi hai ngày, mình xếp mọi thứ định mang lên giường rồi bỏ lại những món chỉ dành cho các tình huống khó xảy ra. Mình giữ quần áo phù hợp thời tiết, giấy tờ, thuốc cần dùng và một chai nước.",
      "Chiếc túi nhẹ khiến việc lên tàu và đi bộ dễ chịu hơn. Mình vẫn kiểm tra những thứ thiết yếu, nhưng không cố mang theo cả sự tiện nghi ở nhà. Mang vừa đủ giúp mình quan tâm nhiều hơn đến nơi đang đến thay vì chiếc túi trên vai.",
    ],
    postedDate: "2026-09-24",
    readingTime: "4 phút đọc",
    tags: ["Hành trình"],
  },
  {
    slug: "y-nghia-cua-khoang-lang",
    categorySlug: "suy-nghi",
    title: "Ý nghĩa của khoảng lặng",
    description: "Để tâm trí nghỉ ngơi cũng là một cách tìm lại sự rõ ràng.",
    content: [
      "Mình từng lấp đầy mọi khoảng trống bằng âm nhạc, tin tức hoặc một đoạn video. Một hôm chờ xe mà điện thoại hết pin, mình chỉ ngồi nhìn đường phố. Ban đầu thấy sốt ruột, rồi những suy nghĩ bắt đầu chậm lại.",
      "Từ đó mình thử để một vài khoảng trong ngày không có nội dung mới. Không phải lần nào cũng có ý tưởng hay xuất hiện, nhưng mình dễ nhận ra cảm xúc và chọn việc cần làm hơn. Khoảng lặng không trống rỗng như mình từng nghĩ.",
    ],
    postedDate: "2026-09-02",
    readingTime: "4 phút đọc",
    tags: ["Chiêm nghiệm"],
  },
  {
    slug: "nhung-dieu-minh-co-the-doi",
    categorySlug: "suy-nghi",
    title: "Những điều mình có thể đổi",
    description: "Bắt đầu từ một thói quen nhỏ thay vì chờ đợi thay đổi lớn.",
    content: [
      "Danh sách những điều mình muốn thay đổi từng dài đến mức không biết bắt đầu ở đâu. Mình chọn một việc nhỏ nhất: chuẩn bị đồ cho sáng hôm sau trước khi đi ngủ. Việc ấy chỉ mất vài phút và có kết quả ngay.",
      "Sau một tuần, buổi sáng bớt vội hơn. Mình không thay đổi tất cả cùng lúc, chỉ giữ một việc đủ lâu rồi cân nhắc việc tiếp theo. Những điều nằm trong khả năng của mình có thể nhỏ, nhưng vẫn tạo nên khác biệt thật.",
    ],
    postedDate: "2026-09-04",
    readingTime: "5 phút đọc",
    tags: ["Thói quen", "Cuộc sống"],
  },
  {
    slug: "doc-mot-trang-sach-moi",
    categorySlug: "suy-nghi",
    title: "Đọc một trang sách mới",
    description: "Một ý tưởng trong sách có thể mở ra một góc nhìn khác.",
    content: [
      "Mình đọc được một đoạn viết về cách đặt câu hỏi trước khi đưa ra kết luận. Đóng sách lại, mình nhớ đến một cuộc trò chuyện mà bản thân đã hiểu quá nhanh theo kinh nghiệm riêng.",
      "Hôm sau, mình thử hỏi thêm thay vì đoán ý người khác. Câu trả lời khiến mình thấy câu chuyện có nhiều lớp hơn tưởng tượng. Mình thích sách không chỉ vì những điều học được trong lúc đọc, mà còn vì những thay đổi nhỏ sau khi gấp trang cuối.",
    ],
    postedDate: "2026-09-06",
    readingTime: "4 phút đọc",
    tags: ["Sách"],
  },
  {
    slug: "dung-so-bat-dau-lai",
    categorySlug: "suy-nghi",
    title: "Đừng sợ bắt đầu lại",
    description: "Nhìn một khởi đầu mới như cơ hội hiểu mình hơn.",
    content: [
      "Khi một kế hoạch không còn phù hợp, điều khó nhất với mình là chấp nhận thời gian đã dành cho nó. Mình sợ bắt đầu lại nghĩa là trở về con số không, dù thực tế đã có thêm kinh nghiệm và hiểu rõ điều cần tránh.",
      "Mình viết ra những gì có thể mang theo từ chặng đường cũ và chọn một bước thử nhỏ cho hướng mới. Khởi đầu lần này không giống lần đầu. Mình có thể đi chậm hơn, nhưng cũng biết hỏi đúng câu hỏi và tìm sự hỗ trợ sớm hơn.",
    ],
    postedDate: "2026-09-08",
    readingTime: "5 phút đọc",
    tags: ["Chiêm nghiệm"],
  },
  {
    slug: "khi-minh-noi-khong",
    categorySlug: "suy-nghi",
    title: "Khi mình nói không",
    description: "Giữ một ranh giới rõ ràng để dành thời gian cho điều quan trọng.",
    content: [
      "Có lần mình nhận thêm một việc chỉ vì ngại từ chối, rồi không còn thời gian cho việc đã hứa trước đó. Mình nhận ra một lời đồng ý vội có thể khiến cả mình và người nhờ đều thất vọng.",
      "Giờ mình kiểm tra lịch và khả năng trước khi trả lời. Nếu không thể làm, mình nói rõ và ngắn gọn, không đưa ra lời hứa mơ hồ. Một ranh giới rõ ràng giúp những lời đồng ý còn lại đáng tin cậy hơn.",
    ],
    postedDate: "2026-09-14",
    readingTime: "4 phút đọc",
    tags: ["Cuộc sống"],
  },
  {
    slug: "lam-it-nhung-tron-ven",
    categorySlug: "suy-nghi",
    title: "Làm ít nhưng trọn vẹn",
    description: "Sự tập trung đôi khi có giá trị hơn một danh sách công việc dài.",
    content: [
      "Một ngày mở quá nhiều việc cùng lúc, mình liên tục chuyển cửa sổ mà chẳng hoàn thành được bao nhiêu. Mình thử chọn một việc quan trọng, tắt bớt thông báo và dành riêng một khoảng thời gian cho nó.",
      "Khi việc đầu tiên xong, mình mới chọn việc tiếp theo. Danh sách cuối ngày ngắn hơn, nhưng kết quả rõ ràng hơn. Làm ít ở đây không phải giảm sự quan tâm, mà là dành đủ sự chú ý cho từng điều đã chọn.",
    ],
    postedDate: "2026-09-16",
    readingTime: "5 phút đọc",
    tags: ["Công việc", "Thói quen"],
  },
  {
    slug: "nhin-lai-mot-tuan",
    categorySlug: "suy-nghi",
    title: "Nhìn lại một tuần",
    description: "Dành vài phút ghi lại những điều đã học và những điều muốn giữ.",
    content: [
      "Cuối tuần, mình mở sổ và viết ba điều: việc đã hoàn thành, điều khiến mình mất sức và một khoảnh khắc muốn nhớ. Không chấm điểm cả tuần, mình chỉ muốn nhìn rõ hơn những gì đã diễn ra.",
      "Có tuần tiến độ không như dự định nhưng mình đã nghỉ ngơi tốt hơn hoặc dành thời gian cho gia đình. Nhìn lại giúp mình điều chỉnh tuần tới bằng thông tin thật, thay vì cảm giác chung rằng mình chưa làm đủ.",
    ],
    postedDate: "2026-09-18",
    readingTime: "3 phút đọc",
    tags: ["Chiêm nghiệm"],
  },
  {
    slug: "mot-cau-hoi-danh-cho-minh",
    categorySlug: "suy-nghi",
    title: "Một câu hỏi dành cho mình",
    description: "Điều gì thực sự khiến ta thấy một ngày có ý nghĩa?",
    content: [
      "Mình thường nhớ một ngày qua số việc đã làm xong. Nhưng khi nghĩ về những ngày đáng quý nhất, điều hiện ra lại là một cuộc nói chuyện chân thành, một việc giúp được ai đó hoặc thời gian làm điều mình yêu thích.",
      "Mình bắt đầu hỏi mỗi sáng: hôm nay muốn dành sự chú ý cho điều gì? Câu trả lời không phải lúc nào cũng lớn lao. Chỉ cần nó phù hợp với điều mình coi trọng, một ngày bình thường cũng có thể mang ý nghĩa riêng.",
    ],
    postedDate: "2026-09-24",
    readingTime: "4 phút đọc",
    tags: ["Cuộc sống"],
  },
  {
    slug: "chiec-ve-tau-nam-cu",
    categorySlug: "ky-niem",
    title: "Chiếc vé tàu năm cũ",
    description: "Một mẩu giấy nhỏ gợi lại cả chuyến đi và những người đã gặp.",
    content: [
      "Chiếc vé nằm giữa hai trang sách, chữ đã nhạt ở một góc. Mình nhớ lần ấy ra ga sớm, mua đồ ăn cho cả nhóm rồi ngồi đợi chuyến tàu trong sự háo hức rất khó ngủ yên.",
      "Địa điểm của chuyến đi bây giờ đã thay đổi nhiều, nhưng chiếc vé vẫn đưa mình về đúng buổi sáng ấy. Mình đặt nó vào một phong bì cùng vài tấm ảnh. Có những món đồ không còn công dụng, chỉ còn nhiệm vụ giữ một câu chuyện.",
    ],
    postedDate: "2026-09-02",
    readingTime: "3 phút đọc",
    tags: ["Ký ức", "Hành trình"],
  },
  {
    slug: "san-truong-ngay-ay",
    categorySlug: "ky-niem",
    title: "Sân trường ngày ấy",
    description: "Nhớ tiếng trống, hàng cây và những câu chuyện giờ ra chơi.",
    content: [
      "Đi ngang một ngôi trường lúc tan học, mình nghe tiếng gọi nhau và nhớ sân trường cũ. Ngày đó, giờ ra chơi ngắn đến mức chưa kể hết một câu chuyện thì tiếng trống đã vang lên.",
      "Mình nhớ chỗ ngồi dưới gốc cây, những lần chia nhau đồ ăn và cả những lo lắng từng thấy rất lớn. Nhiều điều đã quên, nhưng cảm giác được lớn lên cùng bạn bè vẫn còn nguyên mỗi khi nghe âm thanh quen thuộc ấy.",
    ],
    postedDate: "2026-09-04",
    readingTime: "4 phút đọc",
    tags: ["Tuổi học trò"],
  },
  {
    slug: "bua-com-cung-gia-dinh",
    categorySlug: "ky-niem",
    title: "Bữa cơm cùng gia đình",
    description: "Có những hương vị luôn đưa mình trở về một căn nhà quen.",
    content: [
      "Về nhà vào cuối tuần, mình thấy trên bàn những món quen chẳng cần hỏi trước. Trong bếp, mọi người vừa nấu vừa kể chuyện vụn vặt. Mình phụ xếp bát và nhận ra đã lâu chưa có một bữa ăn không phải nhìn đồng hồ.",
      "Chúng mình nói về cây ngoài sân, người hàng xóm mới và dự định tuần tới. Không có câu chuyện nào đặc biệt, nhưng chính sự bình thường ấy khiến mình thấy được trở về. Mùi món ăn đôi khi lưu giữ một căn nhà rõ hơn cả tấm ảnh.",
    ],
    postedDate: "2026-09-06",
    readingTime: "4 phút đọc",
    tags: ["Gia đình"],
  },
  {
    slug: "la-thu-trong-ngan-keo",
    categorySlug: "ky-niem",
    title: "Lá thư trong ngăn kéo",
    description: "Đọc lại những dòng chữ cũ và gặp một phiên bản khác của mình.",
    content: [
      "Lá thư được gấp làm tư, nét chữ quen nhưng cách nói có phần ngây ngô. Mình đọc lại những dự định ngày trước và mỉm cười vì có điều đã thành, có điều mình không còn muốn nữa.",
      "Thay vì tiếc những kế hoạch chưa thực hiện, mình thấy thương người đã viết lá thư đó. Mình cất lại nó và viết thêm vài dòng về hiện tại. Có lẽ một ngày khác, những dòng hôm nay cũng sẽ giúp mình hiểu chặng đường đã đi.",
    ],
    postedDate: "2026-09-08",
    readingTime: "3 phút đọc",
    tags: ["Ký ức"],
  },
  {
    slug: "ngay-dau-den-thanh-pho",
    categorySlug: "ky-niem",
    title: "Ngày đầu đến thành phố",
    description: "Chiếc ba lô, con đường lạ và cảm giác vừa háo hức vừa bỡ ngỡ.",
    content: [
      "Ngày đầu đến thành phố, mình phải xem bản đồ ngay cả khi đi mua một bữa ăn. Căn phòng mới còn trống, chiếc ba lô đặt ở góc nhà và mọi âm thanh bên ngoài đều lạ.",
      "Rồi mình biết quán ăn gần nhất, nhớ đường về và có người để chào khi đi ngang. Thành phố không trở nên quen trong một ngày. Nó dần thành một phần cuộc sống qua những việc nhỏ lặp lại, cho đến khi mình gọi nơi ấy là nhà.",
    ],
    postedDate: "2026-09-14",
    readingTime: "5 phút đọc",
    tags: ["Khởi đầu", "Ký ức"],
  },
  {
    slug: "bai-hat-cua-mot-thoi",
    categorySlug: "ky-niem",
    title: "Bài hát của một thời",
    description: "Một giai điệu quen bất ngờ mang về những câu chuyện xa.",
    content: [
      "Một bài hát cũ vang lên ở quán và mình nhận ra ngay từ những nốt đầu. Mình nhớ chiếc tai nghe ngày trước, đoạn đường thường đi và người đã gửi cho mình bài hát ấy.",
      "Về nhà, mình nghe lại cả danh sách nhạc của thời đó. Có bài không còn hợp sở thích, nhưng vẫn khiến mình nhớ rất rõ một quãng đời. Âm nhạc giữ ký ức theo một cách riêng, không cần kể lại câu chuyện mà vẫn làm nó trở về.",
    ],
    postedDate: "2026-09-16",
    readingTime: "3 phút đọc",
    tags: ["Âm nhạc"],
  },
  {
    slug: "cuoc-hen-voi-ban-cu",
    categorySlug: "ky-niem",
    title: "Cuộc hẹn với bạn cũ",
    description: "Gặp lại nhau và nhận ra có những điều vẫn không thay đổi.",
    content: [
      "Chúng mình chọn một quán dễ tìm và phải đổi lịch hai lần mới gặp được nhau. Ban đầu ai cũng kể nhanh về công việc, chỗ ở, những thay đổi gần đây. Rồi một câu đùa cũ khiến cả bàn bật cười.",
      "Khoảng cách nhiều năm dường như ngắn lại trong khoảnh khắc ấy. Mọi người đã khác, nhưng cách quan tâm và lắng nghe vẫn quen. Khi ra về, chúng mình không hứa một lịch gặp thật xa, chỉ thống nhất sẽ chủ động hỏi thăm nhau thường hơn.",
    ],
    postedDate: "2026-09-18",
    readingTime: "4 phút đọc",
    tags: ["Bạn bè"],
  },
  {
    slug: "can-phong-cua-tuoi-tho",
    categorySlug: "ky-niem",
    title: "Căn phòng của tuổi thơ",
    description: "Những món đồ nhỏ và góc cửa sổ vẫn còn trong trí nhớ.",
    content: [
      "Căn phòng ngày trước đã được sắp xếp lại, nhưng cửa sổ vẫn nhìn ra khoảng sân quen. Mình đứng ở chỗ từng kê bàn học và nhớ những buổi chiều làm bài trong tiếng người nhà trò chuyện.",
      "Một món đồ nhỏ còn sót trên kệ khiến mình nhớ thêm bao nhiêu chuyện. Mình không cần mọi thứ ở nguyên vị trí cũ để cảm thấy gắn bó. Căn phòng đã thay đổi cùng gia đình, còn phần tuổi thơ ấy vẫn có chỗ trong mình.",
    ],
    postedDate: "2026-09-24",
    readingTime: "4 phút đọc",
    tags: ["Tuổi thơ", "Gia đình"],
  },
];