export const CATEGORIES = [
  {
    name: "Tâm trạng",
    slug: "tam-trang",
    link: "/categories/tam-trang",
    count: 10,
    description: "Những suy nghĩ và cảm xúc đời thường",
    image: "/images/categories/tam-trang.jpg",
    alt: "Sóng biển nhẹ nhàng vỗ vào bờ",
  },
  {
    name: "Vi vu",
    slug: "vi-vu",
    link: "/categories/vi-vu",
    count: 10,
    description: "Những chuyến đi và nơi chốn đã ghé qua",
    image: "/images/categories/vi-vu.jpg",
    alt: "Phong cảnh núi non",
  },
  {
    name: "Suy nghĩ",
    slug: "suy-nghi",
    link: "/categories/suy-nghi",
    count: 10,
    description: "Những góc nhìn và chiêm nghiệm về cuộc sống",
    image: "/images/categories/suy-nghi.jpg",
    alt: "Trang sách và góc viết yên tĩnh",
  },
  {
    name: "Kỷ niệm",
    slug: "ky-niem",
    link: "/categories/ky-niem",
    count: 10,
    description: "Những khoảnh khắc và câu chuyện đáng nhớ",
    image: "/images/categories/ky-niem.jpg",
    alt: "Chiếc máy ảnh lưu giữ những khoảnh khắc",
  },
];

export const BLOG_POSTS = [
  {
    slug: "mot-ngay-cham-lai",
    categorySlug: "tam-trang",
    title: "Một ngày chậm lại",
    description: "Dành một chút thời gian để lắng nghe mình giữa những ngày bận rộn.",
    postedDate: "2026-09-20",
    readingTime: "4 phút đọc",
    tags: ["Đời thường", "Bình yên"],
  },
  {
    slug: "nhung-ngay-long-nhe-tenh",
    categorySlug: "tam-trang",
    title: "Những ngày lòng nhẹ tênh",
    description: "Niềm vui đôi khi đến từ những điều nhỏ bé mà ta thường bỏ qua.",
    postedDate: "2026-10-01",
    readingTime: "3 phút đọc",
    tags: ["Cảm xúc"],
  },
  {
    slug: "hen-voi-nui-non",
    categorySlug: "vi-vu",
    title: "Hẹn với núi non",
    description: "Một chuyến đi giữa những con đường quanh co và khoảng trời rộng mở.",
    postedDate: "2026-09-25",
    readingTime: "6 phút đọc",
    tags: ["Du lịch", "Thiên nhiên"],
  },
  {
    slug: "di-de-tim-mot-khoang-lang",
    categorySlug: "vi-vu",
    title: "Đi để tìm một khoảng lặng",
    description: "Rời nhịp sống quen thuộc để khám phá một nơi chốn mới.",
    postedDate: "2026-09-10",
    readingTime: "5 phút đọc",
    tags: ["Hành trình"],
  },
  {
    slug: "hoc-cach-lang-nghe",
    categorySlug: "suy-nghi",
    title: "Học cách lắng nghe",
    description: "Những điều ta nhận ra khi dành nhiều thời gian hơn để lắng nghe.",
    postedDate: "2026-09-28",
    readingTime: "5 phút đọc",
    tags: ["Chiêm nghiệm"],
  },
  {
    slug: "khong-can-voi-vang",
    categorySlug: "suy-nghi",
    title: "Không cần vội vàng",
    description: "Mỗi người có một nhịp đi riêng, và ta có thể bước theo nhịp của mình.",
    postedDate: "2026-09-12",
    readingTime: "4 phút đọc",
    tags: ["Cuộc sống"],
  },
  {
    slug: "nhung-tam-anh-cu",
    categorySlug: "ky-niem",
    title: "Những tấm ảnh cũ",
    description: "Lật lại một album ảnh và nhớ về những ngày đã qua.",
    postedDate: "2026-09-22",
    readingTime: "3 phút đọc",
    tags: ["Ảnh", "Ký ức"],
  },
  {
    slug: "mua-he-nam-ay",
    categorySlug: "ky-niem",
    title: "Mùa hè năm ấy",
    description: "Một câu chuyện nhỏ về mùa hè, bạn bè và những khoảnh khắc còn ở lại.",
    postedDate: "2026-09-05",
    readingTime: "4 phút đọc",
    tags: ["Ký ức"],
  },
  {
    slug: "buoi-sang-ben-cua-so",
    categorySlug: "tam-trang",
    title: "Buổi sáng bên cửa sổ",
    description: "Một tách trà ấm và ánh nắng đầu ngày đủ để lòng dịu lại.",
    postedDate: "2026-09-02",
    readingTime: "3 phút đọc",
    tags: ["Bình yên"],
  },
  {
    slug: "khi-con-mua-ghe-qua",
    categorySlug: "tam-trang",
    title: "Khi cơn mưa ghé qua",
    description: "Nghe tiếng mưa và để những lo âu trôi đi một chút.",
    postedDate: "2026-09-04",
    readingTime: "4 phút đọc",
    tags: ["Cảm xúc", "Mưa"],
  },
  {
    slug: "cho-minh-mot-ngay-nghi",
    categorySlug: "tam-trang",
    title: "Cho mình một ngày nghỉ",
    description: "Không cần làm điều gì lớn lao trong một ngày dành riêng cho mình.",
    postedDate: "2026-09-06",
    readingTime: "3 phút đọc",
    tags: ["Đời thường"],
  },
  {
    slug: "niem-vui-tu-can-bep-nho",
    categorySlug: "tam-trang",
    title: "Niềm vui từ căn bếp nhỏ",
    description: "Nấu một món quen và tìm lại cảm giác ấm áp giữa ngày dài.",
    postedDate: "2026-09-08",
    readingTime: "4 phút đọc",
    tags: ["Đời thường", "Niềm vui"],
  },
  {
    slug: "nhung-luc-thay-minh-met",
    categorySlug: "tam-trang",
    title: "Những lúc thấy mình mệt",
    description: "Học cách nhận ra giới hạn và đối xử nhẹ nhàng hơn với bản thân.",
    postedDate: "2026-09-14",
    readingTime: "5 phút đọc",
    tags: ["Cảm xúc"],
  },
  {
    slug: "mot-loi-hoi-tham",
    categorySlug: "tam-trang",
    title: "Một lời hỏi thăm",
    description: "Đôi khi một câu hỏi giản dị cũng có thể làm sáng cả ngày.",
    postedDate: "2026-09-16",
    readingTime: "3 phút đọc",
    tags: ["Kết nối"],
  },
  {
    slug: "buoc-chan-cuoi-chieu",
    categorySlug: "tam-trang",
    title: "Bước chân cuối chiều",
    description: "Một vòng đi bộ qua phố quen để sắp xếp lại những cảm xúc trong lòng.",
    postedDate: "2026-09-18",
    readingTime: "4 phút đọc",
    tags: ["Bình yên", "Đời thường"],
  },
  {
    slug: "giu-lai-mot-chut-am-ap",
    categorySlug: "tam-trang",
    title: "Giữ lại một chút ấm áp",
    description: "Ghi lại những điều tử tế nhỏ bé đã gặp trong tuần.",
    postedDate: "2026-09-24",
    readingTime: "3 phút đọc",
    tags: ["Niềm vui"],
  },
  {
    slug: "buoi-sang-o-thanh-pho-la",
    categorySlug: "vi-vu",
    title: "Buổi sáng ở thành phố lạ",
    description: "Khám phá những con phố mới khi hàng quán vừa mở cửa.",
    postedDate: "2026-09-02",
    readingTime: "5 phút đọc",
    tags: ["Du lịch", "Thành phố"],
  },
  {
    slug: "con-duong-ven-bien",
    categorySlug: "vi-vu",
    title: "Con đường ven biển",
    description: "Theo một cung đường đầy gió và dừng lại trước màu xanh của biển.",
    postedDate: "2026-09-04",
    readingTime: "6 phút đọc",
    tags: ["Biển", "Hành trình"],
  },
  {
    slug: "mot-dem-cam-trai",
    categorySlug: "vi-vu",
    title: "Một đêm cắm trại",
    description: "Dựng lều, nấu bữa tối và ngắm bầu trời xa ánh đèn thành phố.",
    postedDate: "2026-09-06",
    readingTime: "5 phút đọc",
    tags: ["Cắm trại", "Thiên nhiên"],
  },
  {
    slug: "ghe-tham-ngoi-lang-nho",
    categorySlug: "vi-vu",
    title: "Ghé thăm ngôi làng nhỏ",
    description: "Những mái nhà yên tĩnh và câu chuyện gặp dọc đường.",
    postedDate: "2026-09-08",
    readingTime: "4 phút đọc",
    tags: ["Du lịch"],
  },
  {
    slug: "chuyen-tau-cuoi-tuan",
    categorySlug: "vi-vu",
    title: "Chuyến tàu cuối tuần",
    description: "Nhìn phong cảnh qua ô cửa và tận hưởng một hành trình chậm rãi.",
    postedDate: "2026-09-14",
    readingTime: "5 phút đọc",
    tags: ["Tàu hỏa", "Hành trình"],
  },
  {
    slug: "di-bo-giua-rung-xanh",
    categorySlug: "vi-vu",
    title: "Đi bộ giữa rừng xanh",
    description: "Một lối mòn dưới tán cây và những âm thanh dễ bỏ quên.",
    postedDate: "2026-09-16",
    readingTime: "6 phút đọc",
    tags: ["Thiên nhiên"],
  },
  {
    slug: "quan-ca-phe-tren-doi",
    categorySlug: "vi-vu",
    title: "Quán cà phê trên đồi",
    description: "Một điểm dừng nhỏ để ngắm mây và trò chuyện cùng bạn đồng hành.",
    postedDate: "2026-09-18",
    readingTime: "4 phút đọc",
    tags: ["Cà phê", "Du lịch"],
  },
  {
    slug: "hanh-ly-cho-chuyen-di-ngan",
    categorySlug: "vi-vu",
    title: "Hành lý cho chuyến đi ngắn",
    description: "Mang theo vừa đủ để dành chỗ cho những trải nghiệm mới.",
    postedDate: "2026-09-24",
    readingTime: "4 phút đọc",
    tags: ["Hành trình"],
  },
  {
    slug: "y-nghia-cua-khoang-lang",
    categorySlug: "suy-nghi",
    title: "Ý nghĩa của khoảng lặng",
    description: "Để tâm trí nghỉ ngơi cũng là một cách tìm lại sự rõ ràng.",
    postedDate: "2026-09-02",
    readingTime: "4 phút đọc",
    tags: ["Chiêm nghiệm"],
  },
  {
    slug: "nhung-dieu-minh-co-the-doi",
    categorySlug: "suy-nghi",
    title: "Những điều mình có thể đổi",
    description: "Bắt đầu từ một thói quen nhỏ thay vì chờ đợi thay đổi lớn.",
    postedDate: "2026-09-04",
    readingTime: "5 phút đọc",
    tags: ["Thói quen", "Cuộc sống"],
  },
  {
    slug: "doc-mot-trang-sach-moi",
    categorySlug: "suy-nghi",
    title: "Đọc một trang sách mới",
    description: "Một ý tưởng trong sách có thể mở ra một góc nhìn khác.",
    postedDate: "2026-09-06",
    readingTime: "4 phút đọc",
    tags: ["Sách"],
  },
  {
    slug: "dung-so-bat-dau-lai",
    categorySlug: "suy-nghi",
    title: "Đừng sợ bắt đầu lại",
    description: "Nhìn một khởi đầu mới như cơ hội hiểu mình hơn.",
    postedDate: "2026-09-08",
    readingTime: "5 phút đọc",
    tags: ["Chiêm nghiệm"],
  },
  {
    slug: "khi-minh-noi-khong",
    categorySlug: "suy-nghi",
    title: "Khi mình nói không",
    description: "Giữ một ranh giới rõ ràng để dành thời gian cho điều quan trọng.",
    postedDate: "2026-09-14",
    readingTime: "4 phút đọc",
    tags: ["Cuộc sống"],
  },
  {
    slug: "lam-it-nhung-tron-ven",
    categorySlug: "suy-nghi",
    title: "Làm ít nhưng trọn vẹn",
    description: "Sự tập trung đôi khi có giá trị hơn một danh sách công việc dài.",
    postedDate: "2026-09-16",
    readingTime: "5 phút đọc",
    tags: ["Công việc", "Thói quen"],
  },
  {
    slug: "nhin-lai-mot-tuan",
    categorySlug: "suy-nghi",
    title: "Nhìn lại một tuần",
    description: "Dành vài phút ghi lại những điều đã học và những điều muốn giữ.",
    postedDate: "2026-09-18",
    readingTime: "3 phút đọc",
    tags: ["Chiêm nghiệm"],
  },
  {
    slug: "mot-cau-hoi-danh-cho-minh",
    categorySlug: "suy-nghi",
    title: "Một câu hỏi dành cho mình",
    description: "Điều gì thực sự khiến ta thấy một ngày có ý nghĩa?",
    postedDate: "2026-09-24",
    readingTime: "4 phút đọc",
    tags: ["Cuộc sống"],
  },
  {
    slug: "chiec-ve-tau-nam-cu",
    categorySlug: "ky-niem",
    title: "Chiếc vé tàu năm cũ",
    description: "Một mẩu giấy nhỏ gợi lại cả chuyến đi và những người đã gặp.",
    postedDate: "2026-09-02",
    readingTime: "3 phút đọc",
    tags: ["Ký ức", "Hành trình"],
  },
  {
    slug: "san-truong-ngay-ay",
    categorySlug: "ky-niem",
    title: "Sân trường ngày ấy",
    description: "Nhớ tiếng trống, hàng cây và những câu chuyện giờ ra chơi.",
    postedDate: "2026-09-04",
    readingTime: "4 phút đọc",
    tags: ["Tuổi học trò"],
  },
  {
    slug: "bua-com-cung-gia-dinh",
    categorySlug: "ky-niem",
    title: "Bữa cơm cùng gia đình",
    description: "Có những hương vị luôn đưa mình trở về một căn nhà quen.",
    postedDate: "2026-09-06",
    readingTime: "4 phút đọc",
    tags: ["Gia đình"],
  },
  {
    slug: "la-thu-trong-ngan-keo",
    categorySlug: "ky-niem",
    title: "Lá thư trong ngăn kéo",
    description: "Đọc lại những dòng chữ cũ và gặp một phiên bản khác của mình.",
    postedDate: "2026-09-08",
    readingTime: "3 phút đọc",
    tags: ["Ký ức"],
  },
  {
    slug: "ngay-dau-den-thanh-pho",
    categorySlug: "ky-niem",
    title: "Ngày đầu đến thành phố",
    description: "Chiếc ba lô, con đường lạ và cảm giác vừa háo hức vừa bỡ ngỡ.",
    postedDate: "2026-09-14",
    readingTime: "5 phút đọc",
    tags: ["Khởi đầu", "Ký ức"],
  },
  {
    slug: "bai-hat-cua-mot-thoi",
    categorySlug: "ky-niem",
    title: "Bài hát của một thời",
    description: "Một giai điệu quen bất ngờ mang về những câu chuyện xa.",
    postedDate: "2026-09-16",
    readingTime: "3 phút đọc",
    tags: ["Âm nhạc"],
  },
  {
    slug: "cuoc-hen-voi-ban-cu",
    categorySlug: "ky-niem",
    title: "Cuộc hẹn với bạn cũ",
    description: "Gặp lại nhau và nhận ra có những điều vẫn không thay đổi.",
    postedDate: "2026-09-18",
    readingTime: "4 phút đọc",
    tags: ["Bạn bè"],
  },
  {
    slug: "can-phong-cua-tuoi-tho",
    categorySlug: "ky-niem",
    title: "Căn phòng của tuổi thơ",
    description: "Những món đồ nhỏ và góc cửa sổ vẫn còn trong trí nhớ.",
    postedDate: "2026-09-24",
    readingTime: "4 phút đọc",
    tags: ["Tuổi thơ", "Gia đình"],
  },
];